// 포트폴리오 콘텐츠 — 출처: 2026 Notion 포트폴리오, yhkwon2004/portfoli 기록 데이터.
// 장면(scene) 순서가 곧 영화의 순서입니다. 3D 연출은 director.js의 SHOTS가 같은 id로 대응합니다.

const M = (file) => `/media/${file}`;

export const profile = {
  name: '권용현',
  en: 'Yonghyun Kwon',
  role: 'Physical AI Developer',
  roleKo: 'AI·소프트웨어·하드웨어를 연결해 현장 문제를 푸는 개발자',
  motto: '제약을 이해하고, 작은 실험으로 해법을 검증합니다.',
  email: 'yhkwon2004@gmail.com',
  links: [
    { label: 'Email', value: 'yhkwon2004@gmail.com', url: 'mailto:yhkwon2004@gmail.com' },
    { label: 'GitHub', value: 'github.com/yhkwon2004', url: 'https://github.com/yhkwon2004' },
    { label: 'Notion', value: '2026 Portfolio', url: 'https://befitting-paper-753.notion.site/2026-1-3f3faf73802f80c7acf6f7c83e9c26e2' },
    { label: 'Instagram', value: '@starring.moon', url: 'https://www.instagram.com/starring.moon/' },
    { label: 'Blog', value: 'blog.naver.com/procmd', url: 'https://blog.naver.com/procmd' },
  ],
};

export const scenes = [
  {
    id: 'intro',
    code: 'BOOT',
    label: 'Opening',
    layout: 'hero',
    hold: 8,
    kicker: 'PORTFOLIO 2026 — PHYSICAL AI',
    title: ['PHYSICAL', 'AI'],
    name: '권용현 · Yonghyun Kwon',
    lead: profile.roleKo,
    tags: ['Drone', 'Robot', 'Mobility', 'AI'],
  },
  {
    id: 'prologue',
    code: 'PROLOGUE',
    label: 'Prologue',
    layout: 'split-left',
    hold: 12,
    kicker: 'PROLOGUE — WHO BUILDS THE MACHINE',
    title: ['제약을 이해하고,', '작은 실험으로', '해법을 검증합니다.'],
    titleKo: true,
    lead:
      '사용자의 불편과 현장의 제약을 구체적인 문제로 정의하고, AI·소프트웨어·하드웨어를 연결해 작동하는 해결책으로 만듭니다. 아이디어 기획부터 알고리즘 구현, 시제품 제작과 검증, 제품화까지 직접 경험해 왔습니다.',
    pillars: [
      { no: '01', title: 'AI · 알고리즘 · 데이터', text: '컴퓨터 비전, 생성형 AI·LLM, 시계열 분석과 시뮬레이션으로 데이터를 문제 해결 흐름에 연결합니다.' },
      { no: '02', title: '임베디드 · 제어 · 모빌리티', text: 'PCB·3D 설계, ESP32 기반 IoT, 로봇·차량·드론으로 하드웨어와 소프트웨어를 통합합니다.' },
      { no: '03', title: '기획 · 제작 · 검증', text: '요구를 정리하고 프로토타입 제작, 테스트와 개선, 협업과 사업화까지 이어갑니다.' },
    ],
    facts: [
      ['EDU', '원광대학교 컴퓨터소프트웨어공학과 · 2023–'],
      ['EDU', 'JST 공유대학 스마트모빌리티 SW공학과 (전북대) 복수전공'],
      ['LAB', '사물인터넷연구실 H/W(PCB·3D) · F/W — 2025–2026'],
    ],
  },
  {
    id: 'aerial',
    code: 'AERIAL',
    label: 'Aerial Autonomy',
    layout: 'split-left',
    hold: 14,
    kicker: 'AERIAL AUTONOMY — 드론',
    title: ['AERIAL', 'AUTONOMY'],
    subtitle: '조종에서 교육, 그리고 자율비행까지',
    lead:
      '2018년 무인멀티콥터 1종 자격으로 시작해 지도조종자(교관)로 드론 교육을 맡았고, Pixhawk·Mission Planner·ROS로 경로를 설계하고 비행을 제어하는 자율비행으로 확장했습니다.',
    stats: [
      { value: '2018', label: '초경량 무인멀티콥터 조종자격 1종' },
      { value: '2024', label: '무인멀티콥터 지도조종자(교관)' },
      { value: '2024–25', label: '드론 교육 교관 활동' },
    ],
    items: [
      { year: '2024', title: 'Pixhawk 자율비행 드론', text: 'Pixhawk와 Mission Planner로 기체를 직접 제작하고 웨이포인트 경로 설정과 비행 제어를 구현했습니다.', tags: ['Pixhawk', 'Mission Planner', 'GPS'] },
      { year: '2023', title: 'ROS 기반 자율주행 경진대회', text: 'Pixhawk·GPS·Mission Planner를 ROS와 연결해 자율주행 로버와 비행 제어 로직을 설계하고 최적화했습니다.', tags: ['ROS', 'Rover', 'Flight Control'], badge: '우수상' },
      { year: '2023', title: '드론 축구', text: '실전 경기로 기체 조작, 팀 전략, 비행 안전과 현장 운용 감각을 익혔습니다.', tags: ['Control', 'Team Play'] },
      { year: '2023', title: '드론 촬영 영상공모전', text: '드론 촬영 기법과 편집으로 대학 전경과 시설을 담은 홍보 영상을 제작했습니다.', tags: ['Aerial Film'], badge: '3위' },
    ],
    media: [
      { type: 'image', src: M('pixhawk-drone.webp'), caption: 'Pixhawk 자율비행 기체 — 조립과 조종기 세팅' },
      { type: 'image', src: M('drone-soccer-field.webp'), caption: '드론 축구 — 실내 경기장 비행·조종 연습' },
    ],
  },
  {
    id: 'ground',
    code: 'GROUND',
    label: 'Ground Mobility',
    layout: 'split-right',
    hold: 16,
    kicker: 'GROUND MOBILITY — 자율주행',
    title: ['GROUND', 'MOBILITY'],
    subtitle: '시뮬레이터에서 배우고, 실차에서 검증한다',
    lead:
      'CARLA·AirSim·Gazebo에서 인지·판단·제어를 설계하고, 유아용 자동차 개조부터 BAJA·EV·Formula 자작차까지 직접 만들고 달렸습니다.',
    items: [
      { year: '2024', title: 'CARLA End-to-End 시뮬레이터', text: 'Unreal Engine·CARLA로 E2E 주행 환경을 구성하고 Python API로 학습 결과를 조향 입력에 연결했습니다. 전이 학습으로 제어 모델을 보완한 1인 프로젝트.', tags: ['CARLA', 'Python', 'Unreal'] },
      { year: 'AI', title: 'AirSim 딥러닝 자율주행', text: '가상환경에서 딥러닝으로 조향과 주차 신호 인식을 학습 — 미래자동차 경진대회 조향·주차 신호인식 부문.', tags: ['AirSim', 'Deep Learning', 'Vision'], badge: '장려상', media: 0 },
      { year: '2024', title: '산업부 주관 자율주행 경진대회', text: '유아용 자동차를 개조해 조향·도로 주행·신호등 인식·주차 로직을 개발하고 대회 환경에서 튜닝했습니다.', tags: ['Signal Recognition', 'Parking'] },
      { year: '2024', title: 'ROS2 Nav2 · Gazebo', text: 'Nav2 경로 계획과 Gazebo·RViz 시뮬레이션으로 자율주행 기초를 반복 실습했습니다.', tags: ['ROS2', 'Nav2', 'RViz'] },
      { year: '2024–25', title: '자작차 BAJA · EV · Formula', text: '자작차 동아리 메카니즘에서 CATIA 프레임 설계, 선반·밀링·용접 가공, 새만금 대회 주행까지. 1mm 오차가 구조 전체를 흔든다는 감각을 얻었습니다.', tags: ['CATIA', 'Machining', 'Vehicle'] },
      { year: '2024–25', title: '에듀카트 · 미래수송기기 해커톤', text: 'Arduino Mega 전원 관리와 브레이크·배터리 센싱을 갖춘 탑승형 카트, 심부전 환자 이송용 자율주행 의료 차량을 설계했습니다.', tags: ['Arduino', 'EV', 'Medical Mobility'], badge: '우수상 ×2' },
    ],
    media: [
      { type: 'video', src: M('airsim-demo.mp4'), poster: M('airsim-poster.webp'), caption: 'AirSim 자율주행 제어 시뮬레이션 — 실제 실험 영상' },
      { type: 'image', src: M('av-track-run.webp'), caption: '자율주행 트랙 주행 실습' },
      { type: 'image', src: M('rviz-path.webp'), caption: 'RViz — Nav2 경로 계획 시각화' },
      { type: 'image', src: M('baja-driving.webp'), caption: '자작차 BAJA 주행 테스트' },
    ],
  },
  {
    id: 'robotics',
    code: 'ROBOTICS',
    label: 'Embodied Robotics',
    layout: 'split-left',
    hold: 14,
    kicker: 'EMBODIED ROBOTICS — 로봇',
    title: ['EMBODIED', 'ROBOTICS'],
    subtitle: '몸을 가진 지능을 설계한다',
    lead:
      '서보와 3D 출력 부품으로 다리를 만들고, 회로를 그리고, 펌웨어를 올립니다. 3D 설계·PCB·모터 제어를 하나로 엮어 실제로 움직이는 기계를 만듭니다.',
    items: [
      { year: '2026', title: '4족보행 로봇', text: '서보모터와 3D 프린팅 부품으로 사족 보행 구조를 조립하고 보행 제어 흐름을 탐색하고 있습니다.', tags: ['Quadruped', 'Servo', '3D Print'], badge: 'NOW' },
      { year: '2026', title: '비전 기반 로봇팔 제어', text: '비전 인식으로 대상을 찾고, 3D로 설계한 로봇팔이 집어 옮기는 제어 흐름을 검토합니다.', tags: ['Robot Arm', 'Vision', '3D Design'] },
      { year: '2023', title: '로봇 밀어내기 해커톤', text: 'Ticket to the Dream — 리프팅·클램핑 메커니즘을 기획하고 3D 모델링, 배선, 모터 제어, 조작 앱을 통합했습니다.', tags: ['Mechanism', 'Motor', 'App'], badge: '최우수상' },
      { year: '2025–26', title: '스마트 IoT 링거폴대', text: 'GTT 알고리즘으로 수액 흐름과 임의 조작을 감시하는 탈부착 장치. ESP32 회로, Altium 60×35mm PCB, Fusion 360 하우징을 맡았습니다.', tags: ['ESP32', 'Altium', 'Fusion 360'], badge: '캡스톤 대상' },
    ],
    media: [
      { type: 'image', src: M('robot-dog.webp'), caption: '4족보행 로봇 — 조립된 프로토타입' },
      { type: 'image', src: M('robot-dog-build.webp'), caption: '서보모터와 출력 부품 조립 과정' },
      { type: 'image', src: M('iot-ring.webp'), caption: '스마트 IoT 링거폴대 — Retrofit 하드웨어 설계' },
      { type: 'image', src: M('iot-pcb.webp'), caption: 'PCB 설계 — 60×35mm 기판 배선 검토' },
    ],
  },
  {
    id: 'intelligence',
    code: 'AI',
    label: 'Machine Intelligence',
    layout: 'split-right',
    hold: 14,
    kicker: 'MACHINE INTELLIGENCE — AI',
    title: ['MACHINE', 'INTELLIGENCE'],
    subtitle: '보고, 이해하고, 정리하는 지능',
    lead:
      '컴퓨터 비전으로 사람의 자세를 읽고, LLM으로 흩어진 기록을 사실관계로 엮습니다. AI가 판단을 대신하기보다 사람의 판단을 돕도록 설계합니다.',
    stats: [
      { value: '2', unit: '위', label: 'HUSS AI 경진대회 — 전국' },
      { value: '33.7', unit: '%', label: '증거 정리 속도 향상 · 50회 테스트' },
    ],
    items: [
      { year: '2026', title: '학교폭력 증거 전처리 LLM 플랫폼', text: '사건 자료를 시간순으로 재구성하고 빠진 증거를 짚어 주는 LLM 시스템. 정보 누락과 AI 환각을 줄이는 방향으로 설계했습니다.', tags: ['LLM', 'Timeline', 'Evidence'], badge: '전국 2위' },
      { year: '2026', title: 'FACTLINE', text: '일상 기록·대화·증거를 타임라인으로 연결하고 상담 준비 보고서를 만드는 서비스.', tags: ['Next.js', 'Vercel AI SDK', 'Prisma'] },
      { year: '2025', title: '작업자 자세감지 iOS 앱', text: 'YOLO 보호구 착용 탐지와 MoveNet 자세 추정을 통합하고 RULA·REBA·OWAS 기준으로 위험 자세를 점수화했습니다.', tags: ['YOLO', 'MoveNet', 'Swift'] },
      { year: '2023–24', title: 'GAN-TTS 산학 프로젝트', text: '사투리까지 자연스러운 한국어 음성 합성 연구 — 학부연구생으로 환경 구축, 음성 데이터 제작, 학습 흐름을 맡았습니다.', tags: ['GAN', 'TTS', 'Linux'] },
    ],
    media: [
      { type: 'image', src: M('posture-yolo.webp'), caption: 'YOLO + MoveNet — 보호구·자세 동시 인식' },
      { type: 'image', src: M('huss-ai.webp'), caption: '2026 HUSS AI 경진대회 수상' },
      { type: 'image', src: M('factline.webp'), caption: 'FACTLINE — 기록을 사실관계로 연결' },
    ],
  },
  {
    id: 'loop',
    code: 'LOOP',
    label: 'Sense · Think · Act',
    layout: 'loop',
    hold: 12,
    kicker: 'THE LOOP — PHYSICAL AI STACK',
    title: ['SENSE.', 'THINK.', 'ACT.'],
    lead:
      '피지컬 AI는 하나의 루프입니다. 센서가 세상을 읽고, 모델이 판단하고, 액추에이터가 움직입니다. 드론·차량·로봇에서 이 루프를 직접 닫아 왔습니다.',
    loop: [
      { key: 'SENSE', ko: '인지', items: ['Camera · Vision', 'LiDAR · GPS · IMU', '압력 · 가스 · 온도 센서', 'ADC 수액 감지'] },
      { key: 'THINK', ko: '판단', items: ['YOLO · MoveNet', 'End-to-End Driving', 'Nav2 Path Planning', 'LLM · Generative AI'] },
      { key: 'ACT', ko: '제어', items: ['Pixhawk Flight Control', 'ESP32 · Arduino F/W', 'Servo · Motor', 'Steering · Brake'] },
      { key: 'BUILD', ko: '제작', items: ['Altium PCB', 'Fusion 360 · Inventor · CATIA', '3D Printing', '선반 · 밀링 · 용접'] },
    ],
    tools: ['Python', 'C#', 'Java', 'Swift', 'TypeScript', 'ROS · ROS2', 'Gazebo', 'CARLA', 'AirSim', 'Unreal Engine', 'Linux', 'AWS'],
  },
  {
    id: 'record',
    code: 'RECORD',
    label: 'The Record',
    layout: 'split-left',
    hold: 14,
    kicker: 'THE RECORD — 수상 · 기록',
    title: ['THE', 'RECORD'],
    counters: [
      { value: 37, label: '수상 기록' },
      { value: 39, label: '프로젝트' },
      { value: 9, label: '자격증' },
      { value: 9, label: '공식 보도' },
    ],
    highlights: [
      { year: '2026', title: 'HUSS AI 경진대회', grade: '전국 2위 · 우수상' },
      { year: '2025', title: 'WON+UP 캡스톤디자인 — IoT 링거폴대', grade: '대상 · 총장상' },
      { year: '2025', title: '전북권 Drive-UP 창업캠프', grade: '대상 · 전북도지사 표창' },
      { year: '2025', title: '근거기반 지역문제 해결 캠프 in 강릉', grade: '대상 · 강릉시장 표창' },
      { year: '2025', title: '전주 청년 창업경진대회', grade: '최우수상 · 전북중기청장 표창' },
      { year: '2025', title: '국가우수 이공계 장학생', grade: '선정' },
      { year: '2024', title: '자율주행 로봇제작·스마트 모빌리티 아이디어', grade: '우수상' },
      { year: '2023', title: 'Ticket to the Dream 해커톤 — 로봇', grade: '최우수상' },
      { year: '2023', title: 'ROS 기반 자율주행 자동차 경진대회', grade: '우수상' },
    ],
    timeline: [
      ['2018', '무인멀티콥터 1종'],
      ['2023', 'LLM 연구실 · GAN-TTS'],
      ['2024', '드론 교관 · 자작차 · 모빌리티 복수전공'],
      ['2025', 'Re:cap 대표 · 전남대 인턴십 우수(1위)'],
      ['2026', 'IoT 연구실 · 4족보행 로봇'],
    ],
  },
  {
    id: 'finale',
    code: 'CREDITS',
    label: 'End Credits',
    layout: 'finale',
    hold: 0,
    kicker: 'END CREDITS',
    credits: [
      ['Directed & Engineered by', '권용현 · Yonghyun Kwon'],
      ['Aerial Unit', 'Pixhawk · Mission Planner · ROS · 드론 교관'],
      ['Ground Unit', 'CARLA · AirSim · ROS2 Nav2 · Gazebo · BAJA / EV / Formula'],
      ['Robotics Unit', '4족보행 로봇 · 로봇팔 · ESP32 · Altium · Fusion 360'],
      ['Intelligence Unit', 'YOLO · MoveNet · LLM · GAN-TTS'],
      ['Education', '원광대학교 컴퓨터소프트웨어공학과 · JST 공유대학 스마트모빌리티 SW공학과'],
      ['Labs', '인공지능 LLM 연구실 · 지능형 IoT 연구실'],
      ['Crew', '자작차 동아리 메카니즘 · Re:cap · 인퓨테크'],
      ['On Location', '익산 · 전주 · 새만금 · 강릉 · 치앙마이'],
      ['Built with', 'Three.js · GSAP · Vite — on Vercel'],
    ],
    end: ['다음 장면은,', '함께 만들 차례입니다.'],
    endEn: 'The next scene is yours.',
  },
];
