// 포트폴리오 콘텐츠 — 출처: 2026 Notion 포트폴리오, yhkwon2004/portfoli 기록 데이터.
// 장면(scene) 순서가 곧 영화의 순서입니다. 3D 연출은 director.js의 SHOTS가 같은 id로 대응합니다.

const M = (file) => `/media/${file}`;

export const profile = {
  name: '권용현',
  en: 'Yonghyun Kwon',
  role: 'Physical AI Developer',
  roleKo: 'AI·소프트웨어·하드웨어를 연결해 현장 문제를 푸는 개발자',
  motto: '제약을 이해하고, 작은 실험으로 해법을 검증합니다.',
  email: 'yhkwon2004@gmail.com',
  links: [
    { label: 'Email', value: 'yhkwon2004@gmail.com', url: 'mailto:yhkwon2004@gmail.com' },
    { label: 'GitHub', value: 'github.com/yhkwon2004', url: 'https://github.com/yhkwon2004' },
    { label: 'Notion', value: '2026 Portfolio', url: 'https://befitting-paper-753.notion.site/2026-1-3f3faf73802f80c7acf6f7c83e9c26e2' },
    { label: 'Instagram', value: '@starring.moon', url: 'https://www.instagram.com/starring.moon/' },
    { label: 'Blog', value: 'blog.naver.com/procmd', url: 'https://blog.naver.com/procmd' },
  ],
};

export const scenes = [
  {
    id: 'intro',
    code: 'BOOT',
    label: 'Opening',
    layout: 'hero',
    hold: 8,
    kicker: 'PORTFOLIO 2026 — PHYSICAL AI',
    title: ['PHYSICAL', 'AI'],
    name: '권용현 · Yonghyun Kwon',
    lead: profile.roleKo,
    tags: ['Drone', 'Robot', 'Mobility', 'AI'],
  },
  {
    id: 'prologue',
    code: 'PROLOGUE',
    label: 'Prologue',
    layout: 'split-left',
    hold: 9,
    kicker: 'PROLOGUE — WHO BUILDS THE MACHINE',
    title: ['제약을 이해하고,', '작은 실험으로', '해법을 검증합니다.'],
    titleKo: true,
    lead: '현장의 제약을 문제로 정의하고, AI·소프트웨어·하드웨어를 연결해 작동하는 해결책으로 만듭니다.',
    pillars: [
      { no: '01', title: 'AI · 알고리즘 · 데이터', text: '비전 · LLM · 시뮬레이션' },
      { no: '02', title: '임베디드 · 제어 · 모빌리티', text: 'PCB · ESP32 · 드론 · 차량 · 로봇' },
      { no: '03', title: '기획 · 제작 · 검증', text: '프로토타입부터 사업화까지' },
    ],
  },
  {
    id: 'aerial',
    code: 'AERIAL',
    label: 'Aerial Autonomy',
    layout: 'reel',
    hold: 11,
    category: 'drone',
    kicker: 'AERIAL AUTONOMY — 드론',
    title: ['AERIAL', 'AUTONOMY'],
    subtitle: '조종에서 교육, 그리고 자율비행까지',
    stats: [
      { value: '2018', label: '멀티콥터 1종' },
      { value: '2024', label: '지도조종자(교관)' },
    ],
    projects: ['pixhawk-drone', 'drone-soccer'],
  },
  {
    id: 'ground',
    code: 'GROUND',
    label: 'Ground Mobility',
    layout: 'reel',
    hold: 12,
    category: 'mobility',
    kicker: 'GROUND MOBILITY — 자율주행 · 차량',
    title: ['GROUND', 'MOBILITY'],
    subtitle: '시뮬레이터에서 배우고, 실차에서 검증한다',
    projects: ['airsim-driving', 'carla-e2e', 'av-competition', 'ros2-nav2', 'baja-ev-formula', 'manual-ev', 'ev-medical', 'ai-pedal-blackbox'],
  },
  {
    id: 'robotics',
    code: 'ROBOTICS',
    label: 'Embodied Robotics',
    layout: 'reel',
    hold: 11,
    category: 'robotics',
    kicker: 'EMBODIED ROBOTICS — 로봇 · 임베디드',
    title: ['EMBODIED', 'ROBOTICS'],
    subtitle: '몸을 가진 지능을 설계한다',
    projects: ['quadruped-robot', 'vision-robot-arm', 'robot-push-hackathon', 'iot-iv-pole', 'pressure-clicker', 'growth-footrest'],
  },
  {
    id: 'intelligence',
    code: 'AI',
    label: 'Machine Intelligence',
    layout: 'reel',
    hold: 12,
    category: 'ai',
    kicker: 'MACHINE INTELLIGENCE — AI',
    title: ['MACHINE', 'INTELLIGENCE'],
    subtitle: '보고, 이해하고, 정리하는 지능',
    stats: [
      { value: '전국 2위', label: 'HUSS AI 경진대회' },
      { value: '33.7%', label: '증거 정리 속도 향상' },
    ],
    projects: ['huss-evidence-ai', 'legal-ai-platform', 'factline', 'worker-posture-ios', 'gan-tts', 'ai-detector', 'ai-pose-guide'],
  },
  {
    id: 'loop',
    code: 'LOOP',
    label: 'Sense · Think · Act',
    layout: 'loop',
    hold: 12,
    kicker: 'THE LOOP — PHYSICAL AI STACK',
    title: ['SENSE.', 'THINK.', 'ACT.'],
    lead:
      '피지컬 AI는 하나의 루프입니다. 센서가 세상을 읽고, 모델이 판단하고, 액추에이터가 움직입니다. 드론·차량·로봇에서 이 루프를 직접 닫아 왔습니다.',
    loop: [
      { key: 'SENSE', ko: '인지', items: ['Camera · Vision', 'LiDAR · GPS · IMU', '압력 · 가스 · 온도 센서', 'ADC 수액 감지'] },
      { key: 'THINK', ko: '판단', items: ['YOLO · MoveNet', 'End-to-End Driving', 'Nav2 Path Planning', 'LLM · Generative AI'] },
      { key: 'ACT', ko: '제어', items: ['Pixhawk Flight Control', 'ESP32 · Arduino F/W', 'Servo · Motor', 'Steering · Brake'] },
      { key: 'BUILD', ko: '제작', items: ['Altium PCB', 'Fusion 360 · Inventor · CATIA', '3D Printing', '선반 · 밀링 · 용접'] },
    ],
    tools: ['Python', 'C#', 'Java', 'Swift', 'TypeScript', 'ROS · ROS2', 'Gazebo', 'CARLA', 'AirSim', 'Unreal Engine', 'Linux', 'AWS'],
  },
  {
    id: 'record',
    code: 'RECORD',
    label: 'The Record',
    layout: 'split-left',
    hold: 12,
    kicker: 'THE RECORD — 수상 · 기록',
    title: ['THE', 'RECORD'],
    counters: [
      { value: 37, label: '수상 기록' },
      { value: 39, label: '프로젝트' },
      { value: 9, label: '자격증' },
      { value: 9, label: '공식 보도' },
    ],
    highlights: [
      { year: '2026', title: 'HUSS AI 경진대회', grade: '전국 2위 · 우수상', link: 'huss-evidence-ai' },
      { year: '2025', title: 'WON+UP 캡스톤디자인 — IoT 링거폴대', grade: '대상 · 총장상', link: 'iot-iv-pole' },
      { year: '2025', title: '전북권 Drive-UP 창업캠프', grade: '대상 · 전북도지사 표창', link: 'recap-jbmotors' },
      { year: '2025', title: '근거기반 지역문제 해결 캠프 in 강릉', grade: '대상 · 강릉시장 표창', link: 'coffee-box' },
      { year: '2025', title: '전주 청년 창업경진대회', grade: '최우수상 · 전북중기청장 표창', link: 'coffee-box' },
      { year: '2025', title: '국가우수 이공계 장학생', grade: '선정' },
      { year: '2024', title: '자율주행 로봇제작·스마트 모빌리티 아이디어', grade: '우수상' },
      { year: '2023', title: 'Ticket to the Dream 해커톤 — 로봇', grade: '최우수상', link: 'robot-push-hackathon' },
      { year: '2023', title: 'ROS 기반 자율주행 자동차 경진대회', grade: '우수상' },
    ],
    timeline: [
      ['2018', '무인멀티콥터 1종'],
      ['2023', 'LLM 연구실 · GAN-TTS'],
      ['2024', '드론 교관 · 자작차 · 모빌리티 복수전공'],
      ['2025', 'Re:cap 대표 · 전남대 인턴십 우수(1위)'],
      ['2026', 'IoT 연구실 · 4족보행 로봇'],
    ],
  },
  {
    id: 'finale',
    code: 'CREDITS',
    label: 'End Credits',
    layout: 'finale',
    hold: 0,
    kicker: 'END CREDITS',
    credits: [
      ['Directed & Engineered by', '권용현 · Yonghyun Kwon'],
      ['Aerial Unit', 'Pixhawk · Mission Planner · ROS · 드론 교관'],
      ['Ground Unit', 'CARLA · AirSim · ROS2 Nav2 · Gazebo · BAJA / EV / Formula'],
      ['Robotics Unit', '4족보행 로봇 · 로봇팔 · ESP32 · Altium · Fusion 360'],
      ['Intelligence Unit', 'YOLO · MoveNet · LLM · GAN-TTS'],
      ['Education', '원광대학교 컴퓨터소프트웨어공학과 · JST 공유대학 스마트모빌리티 SW공학과'],
      ['Labs', '인공지능 LLM 연구실 · 지능형 IoT 연구실'],
      ['Crew', '자작차 동아리 메카니즘 · Re:cap · 인퓨테크'],
      ['On Location', '익산 · 전주 · 새만금 · 강릉 · 치앙마이'],
      ['Built with', 'Three.js · GSAP · Vite — on Vercel'],
    ],
    end: ['다음 장면은,', '함께 만들 차례입니다.'],
    endEn: 'The next scene is yours.',
  },
];
